#!/bin/bash

# programa que recebe dois numeros, mostra o maior e soma dos dois
# entrada: <numero1> <numero2>
# saida: <numero1> é <maior que|menor que|igual a> <numero2>


re='^[0-9]+$' # regex para checar se os numeros são inteiros

while :
do
  echo -n "Digite o primeiro número: "
  read number1
  
  if [[ $number1 =~ $re ]]; then break
  else echo "eu disse número, eu quero números"
  fi
done

while :
do
  echo -n "Digite o segundo número: "
  read number2
  
  if [[ $number2 =~ $re ]]; then break
  else echo "eu disse número, eu quero números"
  fi
done

if [ $number1 -gt $number2 ]; then
  echo "$number1 é maior que $number2"
elif [ $number1 -lt $number2 ]; then
  echo "$number1 é menor que $number2"
else
  echo "$number1 é igual a $number2"
fi

echo "soma $(($number1+$number2))"
