#!/bin/bash
# Programa que recebe dois numeros, mostra o maior e a soma dos dois.
# Entrada: <numero1> <numero2>
# Saída: <numero1> é <maior que|menor que|igual a> <numero2>


re='^[0-9]+$' # regex para checar se os numeros são inteiros

while :
do
  echo -n "Digite o primeiro número: "
  read number1
  
  if [[ $number1 =~ $re ]]; then break
  else echo "Eu disse número, eu quero números! (ง︡'-'︠)ง"
  fi
done

while :
do
  echo -n "Digite o segundo número: "
  read number2
  
  if [[ $number2 =~ $re ]]; then break
  else echo "Eu disse número, eu quero números! (ง︡'-'︠)ง"
  fi
done

if [ $number1 -gt $number2 ]; then
  echo "O $number1 é maior que $number2!"
elif [ $number1 -lt $number2 ]; then
  echo "O $number1 é menor que $number2!"
else
  echo "O $number1 é igual a $number2!"
fi

echo "Soma: $(($number1+$number2))"
