#!/bin/bash

# programa que recebe dois numeros, mostra o maior e soma dos dois
# entrada: <numero1> <numero2>
# saida: <numero1> é <maior que|menor que|igual a> <numero2>

if [ $# -ne 2 ]; then # se nao receber exatamente dois numeros, mostra erro
  echo bruh
  exit
fi

re='^[0-9]+$' # regex para checar se os numeros são inteiros

if ! [[ $1 =~ $re && $2 =~ $re ]] # checa se os numeros são inteiros
then
  echo "quero numeros me da numeros"
  exit
fi

if [ $1 -gt $2 ]; then
  echo "$1 é maior que $2"
elif [ $1 -lt $2 ]; then
  echo "$1 é menor que $2"
else
  echo "$1 é igual a $2"
fi

echo "soma $(($1+$2))"
