#!/bin/bash

re='^[0-9]+$'
reO='^[+-/*]+$'

while :
do
  echo -n "Digite o primeiro número: "
  read num1

  if [[ $num1 =~ $re ]]; then break
  else echo "quero números"
  fi
done

while :
do
  echo -n "Digite o segundo número: "
  read num2

  if [[ $num2 =~ $re ]]; then break
  else echo "quero números"
  fi
done

while :
do
  echo -n "Digite o operanto: "
  read operator

  if [[ $operator =~ $reO ]]; then break
  else echo "quero um operando válido... bruh"
  fi
done

echo $(($num1$operator$num2)) # executa o calculo
