#!/bin/bash

# Programa que recebe um nome de usuário e verifica se ele existe.
# Entrada: <nome de usuario>
# Saida: o usuário <nome de usuário> <existe|não existe>

echo -n "Digite o nome: "
read nome

# lê o arquivo /etc/passwd, filtra o texto para ter apenas o root e usuários humanos,
# filtra o texto para ter apenas os nomes de usuário e verifica se o nome de usuário digitado existe com grep
if [[ -n $(cat /etc/passwd | grep -E 'home|root' | cut -d : -f 1| grep -w -io $nome) ]]
then
  echo "O usuário $nome existe! ٩(˘◡˘)۶"
else
  echo "O usuário $nome não existe! (ง︡'-'︠)ง" 
fi
