#!/bin/bash

# Programa lista todos os arquivos e diretórios do diretório atual,
# colocando um (dir) na frente do nome de diretórios.
# Entrada: <path>
# Saída: <arquivo> <diretorio (dir)> <arquivo> <diretorio (dir)> ...

echo -n "Digite o diretório: "
read dir

[ ! -d "$dir" ] && echo "Diretório inválido! ( ˘︹˘ )" && exit

for bagulho in $(ls $dir) # para cada arquivo ou diretorio do diretorio atual
do 
  echo "$bagulho $([ -d $bagulho ] && echo "(dir)")" # se for diretorio, coloca (dir) na frente do nome
done
