#!/bin/bash

# Programa que recebe um número e imprime todos os pares entre 0 e o número digitado.
# Entrada: <numero>
# Saída: 0 2 4 6 8 10 ... <numero>

pei() {
echo "Quero um número maior do que 0! (ㆆ_ㆆ)" && exit
}

echo -n "Digite um número: "
read num

re='^[0-9]+$' 

! [[ $num =~ $re ]] && pei # checa se o numero é inteiro
[ $num -lt 0 ] && pei # checa se o numero é maior que 0

seq -s " " 0 2 $num # imprime todos os numeros pares entre 0 e o numero digitado, separados por espaco
