#!/bin/bash

# programa que recebe um número e imrpime todos os números pares entre 0 e o número digitado
# entrada: <numero
# saida: 0 2 4 6 8 10 ... <numero>

pei() {
echo "quero um número maior q 0..." && exit
}

echo -n "Manda um número: "
read num

re='^[0-9]+$' 

! [[ $num =~ $re ]] && pei # checa se o numero é inteiro
[ $num -lt 0 ] && pei # checa se o numero é maior que 0

seq -s " " 0 2 $num # imprime todos os numeros pares entre 0 e o numero digitado, separados por espaco
