#!/bin/bash

# programa que recebe o nome de um arquivo e mostra quantos bytes ele tem

echo -n "manda o path do arquivo: "
read file

! [ -f $file ] && echo "quero um arquivo valido" #

echo "o arquivo tem $(wc -c $file | cut -d ' ' -f 1) bytes"

