#!/bin/bash

# Programa que recebe o nome de um arquivo e mostra quantos bytes ele tem!

while :
do
    echo -n "Digite o path do arquivo: "
    read file

    if ! [ -f $file ]; then echo "Quero um arquivo valido! (ㆆ_ㆆ)"
    else break
    fi
done

echo "O arquivo tem $(wc -c $file | cut -d ' ' -f 1) bytes! (>‿◠)✌"

