#!/bin/bash

# Programa que recebe o nome de um arquivo e mostra quantos bytes ele tem!

echo -n "Digite o path do arquivo: "
read file

! [ -f $file ] && echo "Quero um arquivo valido! (ㆆ_ㆆ)" #

echo "O arquivo tem $(wc -c $file | cut -d ' ' -f 1) bytes! (>‿◠)✌"

